PortfolioBundle\Entity\Alertes:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\AlertesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateCreationAlerte:
            type: datetime
            column: date_creation_alerte
        commentaire:
            type: string
            nullable: true
            length: 255
        flag_actif:
            type: integer
            nullable: false
    lifecycleCallbacks: {  }
    manyToOne:
        competence:
            targetEntity: Competences
            inversedBy: alertes
            cascade: [ Persist ]
        utilisateur:
            targetEntity: Utilisateurs
            inversedBy: alertes
            cascade: [ Persist ]
