PortfolioBundle\Entity\Competences:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\CompetencesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelleCompetence:
            type: string
            length: 255
            column: libelle_competence
        dateCreation:
            type: date
            column: date_creation
        dateMaj:
            type: date
            nullable: true
            column: date_maj
    lifecycleCallbacks: {  }

    manyToOne:
        experiences_comp:
            targetEntity: Experiences
            inversedBy: competences
            cascade: [ Persist ]
        cursus_comp:
            targetEntity: Cursus
            inversedBy: competences
            cascade: [ Persist ]
        matrice_comp:
            targetEntity: Matrice
            inversedBy: competences
            cascade: [ Persist ]

    oneToMany:
        user_competences:
            targetEntity: Utilisateurs_competences
            mappedBy: competences