PortfolioBundle\Entity\Experiences:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\ExperiencesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeExperience:
            type: string
            length: 255
            column: type_experience
        dureeExperience:
            type: string
            length: 50
            column: dureeExperience
        descriptionExperience:
            type: string
            length: '500'
            nullable: true
            column: description_experience
    lifecycleCallbacks: {  }

    manyToOne:
        utilisateurs:
            targetEntity: Utilisateurs
            inversedBy: experiences
            cascade: [ Persist ]
        cursus:
            targetEntity: Cursus
            inversedBy: experiences
            cascade: [ Persist ]

    oneToMany: 
        competences:
            targetEntity: Competences
            mappedBy: experiences_comp