PortfolioBundle\Entity\Experiences:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\ExperiencesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeExperience:
            type: string
            length: 255
            column: type_experience
        anneeDebutExperience:
            type: date
            column: date_debut_experience
        anneeFinExperience:
            type: date
            nullable: true
            column: annee_fin_experience
        descriptionExperience:
            type: string
            length: '500'
            nullable: true
            column: description_experience
    lifecycleCallbacks: {  }

    manyToOne:
        utilisateurs_exp:
            targetEntity: Utilisateurs
            inversedBy: experiences
            cascade: [ Persist ]
        cursus_exp:
            targetEntity: Cursus
            inversedBy: experiences
            cascade: [ Persist ]

    oneToMany: 
        competences:
            targetEntity: Competences
            mappedBy: experiences_comp