PortfolioBundle\Entity\Matrice:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\MatriceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        flagActif:
            type: integer
            column: flag_actif
    lifecycleCallbacks: {  }

    oneToMany:
        competences:
            targetEntity: Competences
            mappedBy: matrice_comp

    manyToOne:
        theme_matrice:
            targetEntity: Themes
            inversedBy: matrice
            cascade: [ Persist ]
        s_theme_matrice:
            targetEntity: Sous_themes
            inversedBy: matrice
            cascade: [ Persist ]
        s_s_theme_matrice:
            targetEntity: Sous_sous_themes
            inversedBy: matrice
            cascade: [ Persist ]