PortfolioBundle\Entity\Sous_themes:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\Sous_themesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelleSousTheme:
            type: string
            length: 255
            unique: true
            column: libelle_sous_theme
    lifecycleCallbacks: {  }
