PortfolioBundle\Entity\Types_utilisateur:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\Types_utilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: '500'
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany : 
         utilisateurs:
              targetEntity: Utilisateurs
              mappedBy: type_utilisateur