PortfolioBundle\Entity\Utilisateurs:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\UtilisateursRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomUtilisateur:
            type: string
            length: 255
            column: nom_utilisateur
        prenomUtilisateur:
            type: string
            length: 255
            column: prenom_utilisateur
        mailUtilisateur:
            type: string
            length: 255
            unique: true
            column: mail_utilisateur
        username:
            type: string
            length: 255
            unique: true
            column: username
        password:
            type: string
            length: 255
            column: password
        plainPassword:
            type: string
            length: 4096
            column: plain_password
        numeroMobile:
            type: string
            length: '15'
            nullable: true
            column: numero_mobile
        numeroFixe:
            type: string
            length: '15'
            nullable: true
            column: numero_fixe
        dateInscription:
            type: datetime
            column: date_inscription
        dateMajProfil:
            type: datetime
            nullable: true
            column: date_maj_profil
        adressePostale:
            type: string
            length: 255
            nullable: true
            column: adresse_postale
        ville:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: string
            length: '10'
            nullable: true
            column: code_postal
        dateNaissance:
            type: date
            nullable: true
            column: date_naissance
        urlPhoto:
            type: string
            nullable: true
            column: url_photo
    lifecycleCallbacks: {  }
    manyToOne:  
        type_utilisateur:
            targetEntity: Types_utilisateur
            inversedBy: utilisateurs
            cascade: [ persist ]
    oneToMany:
        experiences:
            targetEntity: Experiences
            mappedBy: utilisateurs
        user_competences:
            targetEntity: Utilisateurs_competences
            mappedBy: utilisateurs
        cup:
            targetEntity: Cursus_utilisateurs_competences
            mappedBy: utilisateurs
        alertes:
            targetEntity: Alertes
            mappedBy: utilisateur