PortfolioBundle\Entity\Validations:
    type: entity
    table: null
    repositoryClass: PortfolioBundle\Repository\ValidationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateValidation:
            type: datetime
            column: date_validation
        commentaire:
            type: string
            length: 255
        typeValid:
            type: string
            length: 25
        idUtilisateurValide:
            type: integer
            column: idUtilisateurValide
        idUtilisateurValidant:
            type: integer
            column: idUtilisateurValidant
        idCompetenceValidee:
            type: integer
            column: idCompetenceValidee
    lifecycleCallbacks: {  }
    
    oneToMany:
        user_competences:
            targetEntity: Utilisateurs_competences
            mappedBy: validations
