# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    PortfolioBundle:Utilisateurs
                property: username
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PROF, ROLE_RECRUTEUR, ROLE_ETUDIANT]
    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: connexion
                check_path: resConnex


    encoders:
        PortfolioBundle\Entity\Utilisateurs: sha512