portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Default:index }

portfolio_css:
    path:     /css 
    defaults: { _controller: PortfolioBundle:Default:css }

experience_defaut:
    path:    /experiences
    defaults: { _controller: PortfolioBundle:Experiences:experiences_defaut }
experience_ajout:
    path:    /experiences/add
    defaults: { _controller: PortfolioBundle:Experiences:experiences_add }

creation_profil:
    path:     /creation_profil 
    defaults: { _controller: PortfolioBundle:Profil:creationProfil }

modification_profil:
    path:     /modification_profil/{id_utilisateur} 
    defaults: { _controller: PortfolioBundle:Profil:modificationProfil }

recherche:
    path:     /recherche
    defaults: { _controller: PortfolioBundle:Recherche:recherche }

rechercheParNom:
    path:     /recherchenom
    defaults: { _controller: PortfolioBundle:Recherche:rechercheNom }
