portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Default:index }

portfolio_css:
    path:     /css 
    defaults: { _controller: PortfolioBundle:Default:css }

experience_defaut:
    path:    /experiences
    defaults: { _controller: PortfolioBundle:Experiences:experiences_defaut }
experience_ajout:
    path:    /experiences/add
    defaults: { _controller: PortfolioBundle:Experiences:experiences_add }
experience_modifier:
    path:    /modifier_experience/{id}
    defaults: { _controller: PortfolioBundle:Experiences:experiences_modifier}
    requirements: 
experience_supprimer:
    path:    /supprimer_experience/{id}
    defaults: { _controller: PortfolioBundle:Experiences:experiences_supprimer}   

creation_profil:
    path:     /creation_profil 
    defaults: { _controller: PortfolioBundle:Profil:creationProfil }

recherche:
    path:     /recherche
    defaults: { _controller: PortfolioBundle:Recherche:recherche }
rechercheParNom:
    path:     /recherchenom
    defaults: { _controller: PortfolioBundle:Recherche:rechercheNom }
rechercheAvancee:
    path:     /rechercheavancee
    defaults: { _controller: PortfolioBundle:Recherche:rechercheAvancee }
resultatRecherche:
    path:     /resultatrecherche
    defaults: { _controller: PortfolioBundle:Recherche:resultatrecherche }
cursus_defaut:
    path:    /cursus
    defaults: { _controller: PortfolioBundle:Cursus:cursus_defaut }
cursus_ajout:
    path:    /cursus/add
    defaults: { _controller: PortfolioBundle:Cursus:cursus_add }
cursus_modifier:
    path:    /modifier_cursus/{id}
    defaults: { _controller: PortfolioBundle:Cursus:cursus_modifier }
cursus_supprimer:
    path:    /supprimer_cursus/{id}
    defaults: { _controller: PortfolioBundle:Cursus:cursus_supprimer }
cup_defaut:
    path:    /cup/{id}
    defaults: { _controller: PortfolioBundle:Cup:cup_defaut }