<?php

namespace PortfolioBundle\Repository;

/**
 * AlertesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertesRepository extends \Doctrine\ORM\EntityRepository
{
}
