<?php

namespace PortfolioBundle\Repository;

/**
 * Cursus_utilisateurs_competencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cursus_utilisateurs_competencesRepository extends \Doctrine\ORM\EntityRepository
{
}
