<?php

namespace PortfolioBundle\Repository;

/**
 * Cursus_utilisateurs_competencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cursus_utilisateurs_competencesRepository extends \Doctrine\ORM\EntityRepository
{
	public function select_distinct($id_user)
	{
		 $qb = $this->createQueryBuilder('a');

 		 $qb->where('a.utilisateurs = :id_user')
      		 ->setParameter('id_user', $id_user)
     		->groupBy('a.cursus', 'DESC');

		return $qb
    	->getQuery()
    	->getResult();
	}
}
