<?php

namespace PortfolioBundle\Repository;

/**
 * MatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceRepository extends \Doctrine\ORM\EntityRepository
{
	public function select_distinct() 
	{
		  $qb = $this->createQueryBuilder('a');
		  $qb->groupBy('a.theme_matrice');
		  return $qb->getQuery()->getResult()
		  ;
	}
}
