<?php

namespace PortfolioBundle\Repository;

/**
 * Sous_themesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_themesRepository extends \Doctrine\ORM\EntityRepository
{
}
