<?php

namespace PortfolioBundle\Repository;

/**
 * Types_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Types_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
