<?php

namespace PortfolioBundle\Repository;

/**
 * Utilisateurs_competencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateurs_competencesRepository extends \Doctrine\ORM\EntityRepository
{
}
