<?php

namespace PortfolioBundle\Repository;

/**
 * ValidationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationsRepository extends \Doctrine\ORM\EntityRepository
{
}
